SELECT * FROM DBA_TABLESPACES;				/* 테이블스페이스의 전체 목록 및 속성	*/									*/
SELECT * FROM DBA_DATA_FILES;				/* 테이블스페이스에 속한 데이터 파일 정보	*/									*/
SELECT * FROM DBA_FREE_SPACE;				/* 테이블스페이스 내의 사용되지 않은 공간	*/

DROP USER bigongja CASCADE;
CREATE USER bigongja
 IDENTIFIED BY "developer9983@"
 DEFAULT TABLESPACE USERS
 TEMPORARY TABLESPACE TEMP;


GRANT CREATE SESSION TO bigongja;

GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO bigongja;

GRANT CREATE SYNONYM TO bigongja;

SELECT * FROM DUAL;


CREATE TABLE TEST_TABLE(
	NO			NUMBER(10)		PRIMARY KEY
   ,TITLE		VARCHAR2(30)	NOT NULL
   ,ACTOR		VARCHAR2(10)	NOT NULL
)TABLESPACE USERS
	PCTFREE 20
	PCTUSED 80
	STORAGE ( 						-- 테이블 사이즈 초기 1MB할당(Default 셋팅)
		INITIAL 1M 					-- 
		NEXT 1M						-- NEXT를 배수로 늘리는게 좋다 최소
		MAXEXTENTS UNLIMITED
	);



