SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_DATA_FILES;
SELECT * FROM DBA_FREE_SPACE;


SELECT * FROM DBA_DATA_FILES;
SELECT * FROM DBA_TEMP_FILES;


SELECT * FROM DBA_SEGMENTS;
SELECT * FROM DBA_EXTENTS;
SELECT * FROM DBA_LOBS;


SELECT * FROM DBA_EXTENTS;


SELECT * FROM DBA_FREE_SPACE;
